version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.4

jobs:
  build:
    executor: gcp-cli/default
    environment:
      CLOUDSDK_PYTHON_SITEPACKAGES: 1
    steps:
      - checkout

      - gcp-cli/install

      - run:
          name: Initialize gcloud CLI to connect to Google Cloud
          command: |
            # Set sudo to work whether logged in as root user or non-root user
            if [[ $EUID == 0 ]]; then export SUDO=""; else export SUDO="sudo"; fi

            # Store service account
            echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json

            # Initialize gcloud CLI
            $SUDO gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT \
              --key-file=${HOME}/gcloud-service-key.json \
                --verbosity=debug

            $SUDO gcloud --quiet config set project $GOOGLE_PROJECT_ID --verbosity=debug
            $SUDO gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE --verbosity=debug

      - run:
          name: set default GCP project
          command: |
            gcloud config set project $GOOGLE_PROJECT_ID --verbosity=debug
            gcloud config set account $GCLOUD_SERVICE_ACCOUNT --verbosity=debug

      - run:
          name: enable api's
          command: |
            $SUDO gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT \
              --key-file=${HOME}/gcloud-service-key.json \
              --verbosity=debug

            gcloud services enable \
              container.googleapis.com \
              containeranalysis.googleapis.com \
              binaryauthorization.googleapis.com --verbosity=debug

      - run:
          name: create BinAuthz-enabled GKE cluster
          command: |
            $SUDO gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT \
              --key-file=${HOME}/gcloud-service-key.json \
              --verbosity=debug

            gcloud beta container clusters create \
              --enable-binauthz \
              --zone $GOOGLE_COMPUTE_ZONE \
              test-cluster --verbosity=debug

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - build:
          context: orb-publishing
