version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.5

jobs:
  build:
    executor: gcp-cli/default
    environment:
      CLOUDSDK_PYTHON_SITEPACKAGES: 1
    steps:
      - checkout

      - gcp-cli/install

      - gcp-cli/initialize

      # - run:
      #     name: set default GCP project
      #     command: |
      #       gcloud config set project $GOOGLE_PROJECT_ID
      #       gcloud config set account $GCLOUD_SERVICE_ACCOUNT

      - run:
          name: enable api's
          command: |
            gcloud services enable \
              serviceusage.googleapis.com \
              container.googleapis.com \
              containeranalysis.googleapis.com \
              binaryauthorization.googleapis.com

      - run:
          name: create BinAuthz-enabled GKE cluster
          command: |
            gcloud auth activate-service-account $GCLOUD_SERVICE_ACCOUNT \
              --key-file=${HOME}/gcloud-service-key.json \

            gcloud beta container clusters delete \
              --enable-binauthz \
              --zone $GOOGLE_COMPUTE_ZONE \
              test-cluster

            gcloud beta container clusters create \
              --enable-binauthz \
              --zone $GOOGLE_COMPUTE_ZONE \
              test-cluster

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - build:
          context: orb-publishing
