version: 2.1

orbs:
  bin-authz: circleci/gcp-binary-authorization@dev:alpha
  gcp-cli: circleci/gcp-cli@1.1.0
  orb-tools: circleci/orb-tools@8.3.0

commands:
  test-commands:
    steps:
      - gcp-cli/install
      - gcp-cli/initialize

      - bin-authz/setup:
          gke-cluster-name: test-cluster

      - bin-authz/create-note:
          attestor: $CIRCLE_USERNAME-$CIRCLE_BUILD_NUM

      - bin-authz/create-attestor:
          attestor: $CIRCLE_USERNAME-$CIRCLE_BUILD_NUM
          keypair-email: rose@circleci.com

      - bin-authz/configure-policy:
          admission-whitelist-patterns: gcr.io/google_containers/*
          default-required-attestors: projects/$GOOGLE_PROJECT_ID/attestors/$CIRCLE_USERNAME
          cluster-specific-rules: true
          cluster-specific-required-attestors: projects/$GOOGLE_PROJECT_ID/attestors/$CIRCLE_USERNAME

      - bin-authz/create-attestation:
          attestor: $CIRCLE_USERNAME-$CIRCLE_BUILD_NUM
          image-path: gcr.io/google-containers/google-containers-test-image
          image-tag: "2017-01-23"
          keypair-email: rose@circleci.com

      - store_artifacts:
          path: /tmp/note_payload.json

      - store_artifacts:
          path: /tmp/policy.yaml

      - store_artifacts:
          path: /tmp/generated_payload.json

jobs:
  test-google:
    executor: bin-authz/google
    steps:
      - test-commands

  test-machine:
    executor: bin-authz/machine
    steps:
      - test-commands

  test-docker:
    executor: gcp-cli/default
    steps:
      - test-commands

# yaml anchor filters
integration-dev_filters: &integration-dev_filters
  branches:
    ignore: /.*/
  tags:
    only: /integration-.*/

integration-master_filters: &integration-master_filters
  branches:
    ignore: /.*/
  tags:
    only: /master-.*/

# test-google-master, test-docker-master, test-machine-master,
prod-deploy_requires: &prod-deploy_requires
  [
    multi-project-create-all-google-master
  ]

delete-attestor: &delete-attestor
  [
    run: {
      when: "always",
      name: "Clean up attestor",
      command: "gcloud alpha container binauthz attestors delete $CIRCLE_USERNAME-$CIRCLE_BUILD_NUM"
    }
  ]

multi-project-create-all-post-steps: &multi-project-create-all-post-steps
  [
    run: {
      when: "always",
      name: "Clean up attestor",
      command: "gcloud alpha container binauthz attestors delete $CIRCLE_USERNAME"
    },
    run: {
      when: "always",
      name: "Clean up GKE cluster",
      command: "gcloud container clusters delete test-cluster"
    },
    run: {
      when: "always",
      name: "Clean up keypair environment variables",
      command: "curl -X DELETE https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar/TEST_PUBLIC_KEY?circle-token=$CIRCLE_TOKEN && curl -X DELETE https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar/TEST_PRIVATE_KEY?circle-token=$CIRCLE_TOKEN"
    }
  ]

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint

      - orb-tools/pack:
          requires:
            - orb-tools/lint

      - orb-tools/publish-dev:
          orb-name: circleci/gcp-binary-authorization
          context: orb-publishing
          requires:
            - orb-tools/pack

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          ssh-fingerprints: 30:41:9c:09:66:60:a9:95:1a:b2:ce:07:22:50:ca:85
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master

      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-master
          context: orb-publishing
          ssh-fingerprints: 30:41:9c:09:66:60:a9:95:1a:b2:ce:07:22:50:ca:85
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master

  integration-tests_prod-release:
    jobs:
      # triggered by non-master branch commits
      - bin-authz/create-attestation:
          name: multi-project-create-all-google-dev
          context: orb-publishing
          run-setup: true
          multi-project-setup: true
          create-new-gke-cluster: true
          gke-cluster-name: test-cluster
          use-existing-keypair: false
          keypair-name: test-keypair
          keypair-email: community/partner@circleci.com
          use-passphrase: true
          keypair-passphrase: TEST_PASSPHRASE
          store-generated-keypair: true
          public-key: TEST_PUBLIC_KEY
          private-key: TEST_PRIVATE_KEY
          configure-policy: true
          image-path: gcr.io/google-containers/google-containers-test-image
          image-tag: "2017-01-23"
          filters: *integration-dev_filters
          post-steps: *multi-project-create-all-post-steps

      # triggered by master branch commits
      - bin-authz/create-attestation:
          name: multi-project-create-all-google-master
          context: orb-publishing
          run-setup: true
          multi-project-setup: true
          create-new-gke-cluster: true
          gke-cluster-name: test-cluster
          use-existing-keypair: false
          keypair-name: test-keypair
          keypair-email: community/partner@circleci.com
          use-passphrase: true
          keypair-passphrase: TEST_PASSPHRASE
          store-generated-keypair: true
          public-key: TEST_PUBLIC_KEY
          private-key: TEST_PRIVATE_KEY
          configure-policy: true
          image-path: gcr.io/google-containers/google-containers-test-image
          image-tag: "2017-01-23"
          filters: *integration-master_filters
          post-steps: *multi-project-create-all-post-steps

      # patch, minor, or major publishing
      - orb-tools/dev-promote-prod:
          name: dev-promote-patch
          context: orb-publishing
          orb-name: circleci/gcp-binary-authorization
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-patch.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-minor
          context: orb-publishing
          orb-name: circleci/gcp-binary-authorization
          release: minor
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-minor.*/

      - orb-tools/dev-promote-prod:
          name: dev-promote-major
          context: orb-publishing
          orb-name: circleci/gcp-binary-authorization
          release: major
          requires: *prod-deploy_requires
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /master-major.*/
