version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.0.4

jobs:
  build:
    executor: gcp-cli/default
    steps:
      - checkout

      - gcp-cli/install
      - gcp-cli/initialize

      - run:
          name: set default GCP project
          command: |
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set account $GCLOUD_SERVICE_ACCOUNT
            gcloud services enable \
              container.googleapis.com \
              containeranalysis.googleapis.com \
              binaryauthorization.googleapis.com
            gcloud beta container clusters create \
              --enable-binauthz \
              --zone $GOOGLE_COMPUTE_ZONE \
              test-cluster

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - build:
          context: orb-publishing
